package: auto_update 
version: '0.1-dev' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/auto_update 


requires:                       
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        install: ^2.9

page:
    title: translate:auto_update_title    
    prio: 100                       
    icon: rex-icon fa-gear

default_config:
    core_patch: 1
    core_minor: 0
    addon_patch: 1
    addon_minor: 1
    addon_major: 0
    next: '1988-10-08 00:00:00'
    ignore: 'project,dummy'
    only_trusted_authors: 0
    trusted_authors: 'yakamara,redaxo,friendsofredaxo,alexplusde,skerbis,thomas_blum'
